@startuml webSocket
!theme amiga
actor "User 1" as U1
collections "Web Socket Server" as WS
actor "User 2" as U2
group User connection
	U1 -\ WS: Login handshake
	WS -/ U1: Confirmation
	U2 -\ WS: Login handshake
	WS -/ U2: Confirmation
end
group Message User to User
	U1 -> WS: Send message
	WS -> U2: Transfer message
end
group WebRTC connection
	U1 -\ WS: RTC Peer Offer
	WS -\ U2: RTC Peer Offer
	loop Generation of candidates
		U1 -\ WS: Ice Candidate
		WS -\ U2: Ice Candidate
		U2 --> U2: Adding Candidate
	end
	U2 -/ WS: RTC Peer Answer
	WS -/ U1: RTC Peer Answer
	U1 -[#red]>o U2: Sending MediaStreamTrack
	loop Generation of candidates
		U2 -/ WS: Ice Candidate
		WS -/ U1: Ice Candidate
		U2 --> U2: Adding Candidate
	end
end
@enduml